"""Rebuild supabase/functions/caption/voice.ts from the two voice packs.

Run after editing a pack:
    python _shared/caption-voice/build-voice.py
"""
import io, json, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
OUT = os.path.join(ROOT, "supabase", "functions", "caption", "voice.ts")

packs = {}
for site in ("welliemd", "zenjessica"):
    packs[site] = io.open(os.path.join(HERE, site + ".md"), encoding="utf-8").read()

lines = ["// Generated by _shared/caption-voice/build-voice.py from the two .md packs. Do not edit here.",
         "export const VOICE: Record<string, string> = {"]
for site, text in packs.items():
    lines.append("  %s: %s," % (site, json.dumps(text)))
lines.append("};")
io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
print("voice.ts rebuilt: %d bytes" % os.path.getsize(OUT))
